
name = "DashFullcalendar"
uuid = "1b08a953-4be3-4667-9a23-03796a0fde2b"
authors = ["Scott Kilgore <skilgore@landmarktx.com>"]
version = "0.1.3"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
